# Generated by Django 2.0 on 2023-05-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread')], default='unread', max_length=10),
        ),
    ]
