# Generated by Django 2.0 on 2023-05-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.CharField(choices=[('read', 'read'), ('unread', 'unread'), ('sent', 'sent')], default='unread', max_length=10),
        ),
    ]
